In [5]:
import pandas as pd
from  sklearn.model_selection import StratifiedShuffleSplit

In [8]:
df_train = pd.read_csv('train_new_bk.csv')

In [9]:
df_train.head()

,Category,DayOfWeek,PdDistrict,X,Y,NumMultCrimes,MultProbs1,MultProbs2,MultProbs3,MultProbs4,...,logodds30,logodds31,logodds32,logodds33,logodds34,logodds35,logodds36,logodds37,logodds38,LogoddsPA
0,WARRANTS,Wednesday,NORTHERN,-122.425892,37.774599,2,-6.541286,-2.109738,-7.718282,-7.741549,...,-5.259591,-7.454398,-3.294016,-11.893691,-4.777894,-2.924890,-1.712979,-2.985679,-4.621396,-9.408710
1,OTHER OFFENSES,Wednesday,NORTHERN,-122.425892,37.774599,2,-6.541286,-2.109738,-7.718282,-7.741549,...,-5.259591,-7.454398,-3.294016,-11.893691,-4.777894,-2.924890,-1.712979,-2.985679,-4.621396,-9.408710
2,OTHER OFFENSES,Wednesday,NORTHERN,-122.424363,37.800414,1,-6.188288,-2.535865,-7.583242,-9.999619,...,-5.259591,-7.454398,-3.294016,-11.893691,-4.777894,-2.924890,-1.704748,-2.985679,-4.621396,-10.021852
3,LARCENY/THEFT,Wednesday,NORTHERN,-122.426995,37.800873,1,-6.188288,-2.535865,-7.583242,-9.999619,...,-5.259591,-7.454398,-3.294016,-11.893691,-4.777894,-3.212187,-2.729575,-2.985679,-4.621396,-8.641856
4,LARCENY/THEFT,Wednesday,PARK,-122.438738,37.771541,1,-6.188288,-2.535865,-7.583242,-9.999619,...,-5.259591,-7.454398,-3.294016,-11.893691,-4.777894,-2.924890,-2.729575,-2.985679,-4.621396,-9.734155

In [10]:
y = df_train['Category']
x = df_train[df_train.columns.difference(['Category'])]

In [11]:
split_f = StratifiedShuffleSplit(1,test_size=0.2,train_size=0.8)

In [20]:
for train_index, test_index in split_f.split(x, y):
    x_train,y_train = x.iloc[train_index],y.iloc[train_index]
    x_test,y_test = x.iloc[test_index],y.iloc[test_index]

In [29]:
train_data = x_train.join(y_train)
test_data = x_test.join(y_test)

In [35]:
train_data.to_csv('train_processed_split.csv')

In [36]:
test_data.to_csv('test_processed_split.csv')

In [34]:
train_data.head()

,Day,DayOfWeek,DayOfYear,Hour,LogoddsPA,Minutes,Month,MultProbs1,MultProbs10,MultProbs11,...,logodds36,logodds37,logodds38,logodds4,logodds5,logodds6,logodds7,logodds8,logodds9,Category
224513,15,Tuesday,136,10,-8.381924,30,5,-6.188288,-6.495606,-8.664491,...,-2.729575,-2.985679,-4.621396,-2.259568,-5.309515,-5.956218,-2.725818,-5.318863,-6.622794,LARCENY/THEFT
541228,21,Friday,264,18,-9.012507,0,9,-6.188288,-6.495606,-8.664491,...,-2.729575,-2.272126,-4.621396,-3.130667,-5.309515,-5.956218,-2.725818,-5.318863,-6.622794,VEHICLE THEFT
132645,9,Friday,221,13,-7.506964,50,8,-6.541286,-6.715363,-7.599166,...,-3.438279,-2.547211,-4.621396,-2.712485,-5.309515,-5.956218,-3.961871,-5.318863,-6.622794,LARCENY/THEFT
25598,9,Friday,9,18,-6.027659,50,1,-7.153636,-7.193276,-7.645534,...,-3.135494,-3.344039,-5.860786,-2.766068,-5.309515,-5.956218,-4.309840,-5.318863,-5.252273,LARCENY/THEFT
74809,16,Friday,136,14,-8.128335,7,5,-6.541286,-6.715363,-7.599166,...,-3.741630,-2.862201,-2.536200,-2.940382,-5.309515,-5.956218,-2.720473,-5.318863,-6.622794,OTHER OFFENSES

In [33]:
len(test_data)

175610